apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: team5
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: "2048Mi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
  restartPolicy: Always
